REST_API_URL = 'http://rest-api:8080'
KEY_DIR = '/root/.sawtooth/keys'
PRIV_KEY_FILE = KEY_DIR + '/key.priv'
PUB_KEY_FILE = KEY_DIR + '/key.pub'

SETTINGS_KEY_PUB_ENCRYPTION_KEY = 'SETTINGS_KEY_PUB_ENCRYPTION_KEY'
SETTINGS_KEY_ALLOWED_GENESIS_MEMBERS = 'SETTINGS_KEY_ALLOWED_GENESIS_MEMBERS'
SETTINGS_SWAP_COMMISSION = 'SETTINGS_SWAP_COMMISSION'
