# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='account.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\raccount.proto\"4\n\rAccountMethod\"#\n\x06Method\x12\x0c\n\x08TRANSFER\x10\x00\x12\x0b\n\x07GENESIS\x10\x01\"4\n\x0fTransferPayload\x12\x12\n\naddress_to\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04\"&\n\x0eGenesisPayload\x12\x14\n\x0ctotal_supply\x18\x01 \x01(\x04\",\n\x07\x41\x63\x63ount\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x04\x12\x10\n\x08pub_keys\x18\x02 \x03(\t\"\x1f\n\rGenesisStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\x62\x06proto3')
)



_ACCOUNTMETHOD_METHOD = _descriptor.EnumDescriptor(
  name='Method',
  full_name='AccountMethod.Method',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRANSFER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENESIS', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=34,
  serialized_end=69,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNTMETHOD_METHOD)


_ACCOUNTMETHOD = _descriptor.Descriptor(
  name='AccountMethod',
  full_name='AccountMethod',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACCOUNTMETHOD_METHOD,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=69,
)


_TRANSFERPAYLOAD = _descriptor.Descriptor(
  name='TransferPayload',
  full_name='TransferPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_to', full_name='TransferPayload.address_to', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TransferPayload.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=123,
)


_GENESISPAYLOAD = _descriptor.Descriptor(
  name='GenesisPayload',
  full_name='GenesisPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_supply', full_name='GenesisPayload.total_supply', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=163,
)


_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='balance', full_name='Account.balance', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pub_keys', full_name='Account.pub_keys', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=209,
)


_GENESISSTATUS = _descriptor.Descriptor(
  name='GenesisStatus',
  full_name='GenesisStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='GenesisStatus.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=242,
)

_ACCOUNTMETHOD_METHOD.containing_type = _ACCOUNTMETHOD
DESCRIPTOR.message_types_by_name['AccountMethod'] = _ACCOUNTMETHOD
DESCRIPTOR.message_types_by_name['TransferPayload'] = _TRANSFERPAYLOAD
DESCRIPTOR.message_types_by_name['GenesisPayload'] = _GENESISPAYLOAD
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
DESCRIPTOR.message_types_by_name['GenesisStatus'] = _GENESISSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountMethod = _reflection.GeneratedProtocolMessageType('AccountMethod', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTMETHOD,
  __module__ = 'account_pb2'
  # @@protoc_insertion_point(class_scope:AccountMethod)
  ))
_sym_db.RegisterMessage(AccountMethod)

TransferPayload = _reflection.GeneratedProtocolMessageType('TransferPayload', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFERPAYLOAD,
  __module__ = 'account_pb2'
  # @@protoc_insertion_point(class_scope:TransferPayload)
  ))
_sym_db.RegisterMessage(TransferPayload)

GenesisPayload = _reflection.GeneratedProtocolMessageType('GenesisPayload', (_message.Message,), dict(
  DESCRIPTOR = _GENESISPAYLOAD,
  __module__ = 'account_pb2'
  # @@protoc_insertion_point(class_scope:GenesisPayload)
  ))
_sym_db.RegisterMessage(GenesisPayload)

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNT,
  __module__ = 'account_pb2'
  # @@protoc_insertion_point(class_scope:Account)
  ))
_sym_db.RegisterMessage(Account)

GenesisStatus = _reflection.GeneratedProtocolMessageType('GenesisStatus', (_message.Message,), dict(
  DESCRIPTOR = _GENESISSTATUS,
  __module__ = 'account_pb2'
  # @@protoc_insertion_point(class_scope:GenesisStatus)
  ))
_sym_db.RegisterMessage(GenesisStatus)


# @@protoc_insertion_point(module_scope)
