# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pub_key.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pub_key.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rpub_key.proto\"/\n\x0cPubKeyMethod\"\x1f\n\x06Method\x12\t\n\x05STORE\x10\x00\x12\n\n\x06REVOKE\x10\x01\"\xa9\x02\n\x10NewPubKeyPayload\x12\x12\n\npublic_key\x18\x01 \x01(\t\x12\x35\n\x0fpublic_key_type\x18\x02 \x01(\x0e\x32\x1c.NewPubKeyPayload.PubKeyType\x12\x31\n\x0b\x65ntity_type\x18\x03 \x01(\x0e\x32\x1c.NewPubKeyPayload.EntityType\x12\x13\n\x0b\x65ntity_hash\x18\x04 \x01(\t\x12\x1d\n\x15\x65ntity_hash_signature\x18\x05 \x01(\t\x12\x12\n\nvalid_from\x18\x06 \x01(\r\x12\x10\n\x08valid_to\x18\x07 \x01(\r\"&\n\nEntityType\x12\x0c\n\x08PERSONAL\x10\x00\x12\n\n\x06SERVER\x10\x01\"\x15\n\nPubKeyType\x12\x07\n\x03RSA\x10\x00\"&\n\x13RevokePubKeyPayload\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"S\n\rPubKeyStorage\x12\r\n\x05owner\x18\x01 \x01(\t\x12\"\n\x07payload\x18\x02 \x01(\x0b\x32\x11.NewPubKeyPayload\x12\x0f\n\x07revoked\x18\x03 \x01(\x08\x62\x06proto3')
)



_PUBKEYMETHOD_METHOD = _descriptor.EnumDescriptor(
  name='Method',
  full_name='PubKeyMethod.Method',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STORE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REVOKE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=33,
  serialized_end=64,
)
_sym_db.RegisterEnumDescriptor(_PUBKEYMETHOD_METHOD)

_NEWPUBKEYPAYLOAD_ENTITYTYPE = _descriptor.EnumDescriptor(
  name='EntityType',
  full_name='NewPubKeyPayload.EntityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PERSONAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=303,
  serialized_end=341,
)
_sym_db.RegisterEnumDescriptor(_NEWPUBKEYPAYLOAD_ENTITYTYPE)

_NEWPUBKEYPAYLOAD_PUBKEYTYPE = _descriptor.EnumDescriptor(
  name='PubKeyType',
  full_name='NewPubKeyPayload.PubKeyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RSA', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=343,
  serialized_end=364,
)
_sym_db.RegisterEnumDescriptor(_NEWPUBKEYPAYLOAD_PUBKEYTYPE)


_PUBKEYMETHOD = _descriptor.Descriptor(
  name='PubKeyMethod',
  full_name='PubKeyMethod',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PUBKEYMETHOD_METHOD,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=64,
)


_NEWPUBKEYPAYLOAD = _descriptor.Descriptor(
  name='NewPubKeyPayload',
  full_name='NewPubKeyPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='NewPubKeyPayload.public_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='public_key_type', full_name='NewPubKeyPayload.public_key_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity_type', full_name='NewPubKeyPayload.entity_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity_hash', full_name='NewPubKeyPayload.entity_hash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity_hash_signature', full_name='NewPubKeyPayload.entity_hash_signature', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_from', full_name='NewPubKeyPayload.valid_from', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_to', full_name='NewPubKeyPayload.valid_to', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NEWPUBKEYPAYLOAD_ENTITYTYPE,
    _NEWPUBKEYPAYLOAD_PUBKEYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=364,
)


_REVOKEPUBKEYPAYLOAD = _descriptor.Descriptor(
  name='RevokePubKeyPayload',
  full_name='RevokePubKeyPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='RevokePubKeyPayload.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=404,
)


_PUBKEYSTORAGE = _descriptor.Descriptor(
  name='PubKeyStorage',
  full_name='PubKeyStorage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='PubKeyStorage.owner', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='PubKeyStorage.payload', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revoked', full_name='PubKeyStorage.revoked', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=489,
)

_PUBKEYMETHOD_METHOD.containing_type = _PUBKEYMETHOD
_NEWPUBKEYPAYLOAD.fields_by_name['public_key_type'].enum_type = _NEWPUBKEYPAYLOAD_PUBKEYTYPE
_NEWPUBKEYPAYLOAD.fields_by_name['entity_type'].enum_type = _NEWPUBKEYPAYLOAD_ENTITYTYPE
_NEWPUBKEYPAYLOAD_ENTITYTYPE.containing_type = _NEWPUBKEYPAYLOAD
_NEWPUBKEYPAYLOAD_PUBKEYTYPE.containing_type = _NEWPUBKEYPAYLOAD
_PUBKEYSTORAGE.fields_by_name['payload'].message_type = _NEWPUBKEYPAYLOAD
DESCRIPTOR.message_types_by_name['PubKeyMethod'] = _PUBKEYMETHOD
DESCRIPTOR.message_types_by_name['NewPubKeyPayload'] = _NEWPUBKEYPAYLOAD
DESCRIPTOR.message_types_by_name['RevokePubKeyPayload'] = _REVOKEPUBKEYPAYLOAD
DESCRIPTOR.message_types_by_name['PubKeyStorage'] = _PUBKEYSTORAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PubKeyMethod = _reflection.GeneratedProtocolMessageType('PubKeyMethod', (_message.Message,), dict(
  DESCRIPTOR = _PUBKEYMETHOD,
  __module__ = 'pub_key_pb2'
  # @@protoc_insertion_point(class_scope:PubKeyMethod)
  ))
_sym_db.RegisterMessage(PubKeyMethod)

NewPubKeyPayload = _reflection.GeneratedProtocolMessageType('NewPubKeyPayload', (_message.Message,), dict(
  DESCRIPTOR = _NEWPUBKEYPAYLOAD,
  __module__ = 'pub_key_pb2'
  # @@protoc_insertion_point(class_scope:NewPubKeyPayload)
  ))
_sym_db.RegisterMessage(NewPubKeyPayload)

RevokePubKeyPayload = _reflection.GeneratedProtocolMessageType('RevokePubKeyPayload', (_message.Message,), dict(
  DESCRIPTOR = _REVOKEPUBKEYPAYLOAD,
  __module__ = 'pub_key_pb2'
  # @@protoc_insertion_point(class_scope:RevokePubKeyPayload)
  ))
_sym_db.RegisterMessage(RevokePubKeyPayload)

PubKeyStorage = _reflection.GeneratedProtocolMessageType('PubKeyStorage', (_message.Message,), dict(
  DESCRIPTOR = _PUBKEYSTORAGE,
  __module__ = 'pub_key_pb2'
  # @@protoc_insertion_point(class_scope:PubKeyStorage)
  ))
_sym_db.RegisterMessage(PubKeyStorage)


# @@protoc_insertion_point(module_scope)
