# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='settings.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0esettings.proto\"O\n\x07Setting\x12\x1f\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0e.Setting.Entry\x1a#\n\x05\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"{\n\x0fSettingsPayload\x12\'\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x17.SettingsPayload.Action\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"1\n\x06\x41\x63tion\x12\x10\n\x0c\x41\x43TION_UNSET\x10\x00\x12\x0b\n\x07PROPOSE\x10\x01\x12\x08\n\x04VOTE\x10\x02\"@\n\x0fSettingProposal\x12\x0f\n\x07setting\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\t\"s\n\x0bSettingVote\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12\x1f\n\x04vote\x18\x02 \x01(\x0e\x32\x11.SettingVote.Vote\".\n\x04Vote\x12\x0e\n\nVOTE_UNSET\x10\x00\x12\n\n\x06\x41\x43\x43\x45PT\x10\x01\x12\n\n\x06REJECT\x10\x02\"\xbb\x01\n\x10SettingCandidate\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12\"\n\x08proposal\x18\x02 \x01(\x0b\x32\x10.SettingProposal\x12+\n\x05votes\x18\x03 \x03(\x0b\x32\x1c.SettingCandidate.VoteRecord\x1a\x41\n\nVoteRecord\x12\x12\n\npublic_key\x18\x01 \x01(\t\x12\x1f\n\x04vote\x18\x02 \x01(\x0e\x32\x11.SettingVote.Vote\":\n\x11SettingCandidates\x12%\n\ncandidates\x18\x01 \x03(\x0b\x32\x11.SettingCandidateB\x1e\n\x1asawtooth.settings.protobufP\x01\x62\x06proto3')
)



_SETTINGSPAYLOAD_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='SettingsPayload.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTION_UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROPOSE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOTE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=173,
  serialized_end=222,
)
_sym_db.RegisterEnumDescriptor(_SETTINGSPAYLOAD_ACTION)

_SETTINGVOTE_VOTE = _descriptor.EnumDescriptor(
  name='Vote',
  full_name='SettingVote.Vote',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VOTE_UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCEPT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REJECT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=359,
  serialized_end=405,
)
_sym_db.RegisterEnumDescriptor(_SETTINGVOTE_VOTE)


_SETTING_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='Setting.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Setting.Entry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Setting.Entry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=97,
)

_SETTING = _descriptor.Descriptor(
  name='Setting',
  full_name='Setting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='Setting.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SETTING_ENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=97,
)


_SETTINGSPAYLOAD = _descriptor.Descriptor(
  name='SettingsPayload',
  full_name='SettingsPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='SettingsPayload.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='SettingsPayload.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETTINGSPAYLOAD_ACTION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=222,
)


_SETTINGPROPOSAL = _descriptor.Descriptor(
  name='SettingProposal',
  full_name='SettingProposal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setting', full_name='SettingProposal.setting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='SettingProposal.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='SettingProposal.nonce', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=288,
)


_SETTINGVOTE = _descriptor.Descriptor(
  name='SettingVote',
  full_name='SettingVote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal_id', full_name='SettingVote.proposal_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vote', full_name='SettingVote.vote', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETTINGVOTE_VOTE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=405,
)


_SETTINGCANDIDATE_VOTERECORD = _descriptor.Descriptor(
  name='VoteRecord',
  full_name='SettingCandidate.VoteRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='SettingCandidate.VoteRecord.public_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vote', full_name='SettingCandidate.VoteRecord.vote', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=595,
)

_SETTINGCANDIDATE = _descriptor.Descriptor(
  name='SettingCandidate',
  full_name='SettingCandidate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal_id', full_name='SettingCandidate.proposal_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proposal', full_name='SettingCandidate.proposal', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='votes', full_name='SettingCandidate.votes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SETTINGCANDIDATE_VOTERECORD, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=595,
)


_SETTINGCANDIDATES = _descriptor.Descriptor(
  name='SettingCandidates',
  full_name='SettingCandidates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='candidates', full_name='SettingCandidates.candidates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=655,
)

_SETTING_ENTRY.containing_type = _SETTING
_SETTING.fields_by_name['entries'].message_type = _SETTING_ENTRY
_SETTINGSPAYLOAD.fields_by_name['action'].enum_type = _SETTINGSPAYLOAD_ACTION
_SETTINGSPAYLOAD_ACTION.containing_type = _SETTINGSPAYLOAD
_SETTINGVOTE.fields_by_name['vote'].enum_type = _SETTINGVOTE_VOTE
_SETTINGVOTE_VOTE.containing_type = _SETTINGVOTE
_SETTINGCANDIDATE_VOTERECORD.fields_by_name['vote'].enum_type = _SETTINGVOTE_VOTE
_SETTINGCANDIDATE_VOTERECORD.containing_type = _SETTINGCANDIDATE
_SETTINGCANDIDATE.fields_by_name['proposal'].message_type = _SETTINGPROPOSAL
_SETTINGCANDIDATE.fields_by_name['votes'].message_type = _SETTINGCANDIDATE_VOTERECORD
_SETTINGCANDIDATES.fields_by_name['candidates'].message_type = _SETTINGCANDIDATE
DESCRIPTOR.message_types_by_name['Setting'] = _SETTING
DESCRIPTOR.message_types_by_name['SettingsPayload'] = _SETTINGSPAYLOAD
DESCRIPTOR.message_types_by_name['SettingProposal'] = _SETTINGPROPOSAL
DESCRIPTOR.message_types_by_name['SettingVote'] = _SETTINGVOTE
DESCRIPTOR.message_types_by_name['SettingCandidate'] = _SETTINGCANDIDATE
DESCRIPTOR.message_types_by_name['SettingCandidates'] = _SETTINGCANDIDATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Setting = _reflection.GeneratedProtocolMessageType('Setting', (_message.Message,), dict(

  Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
    DESCRIPTOR = _SETTING_ENTRY,
    __module__ = 'settings_pb2'
    # @@protoc_insertion_point(class_scope:Setting.Entry)
    ))
  ,
  DESCRIPTOR = _SETTING,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:Setting)
  ))
_sym_db.RegisterMessage(Setting)
_sym_db.RegisterMessage(Setting.Entry)

SettingsPayload = _reflection.GeneratedProtocolMessageType('SettingsPayload', (_message.Message,), dict(
  DESCRIPTOR = _SETTINGSPAYLOAD,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:SettingsPayload)
  ))
_sym_db.RegisterMessage(SettingsPayload)

SettingProposal = _reflection.GeneratedProtocolMessageType('SettingProposal', (_message.Message,), dict(
  DESCRIPTOR = _SETTINGPROPOSAL,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:SettingProposal)
  ))
_sym_db.RegisterMessage(SettingProposal)

SettingVote = _reflection.GeneratedProtocolMessageType('SettingVote', (_message.Message,), dict(
  DESCRIPTOR = _SETTINGVOTE,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:SettingVote)
  ))
_sym_db.RegisterMessage(SettingVote)

SettingCandidate = _reflection.GeneratedProtocolMessageType('SettingCandidate', (_message.Message,), dict(

  VoteRecord = _reflection.GeneratedProtocolMessageType('VoteRecord', (_message.Message,), dict(
    DESCRIPTOR = _SETTINGCANDIDATE_VOTERECORD,
    __module__ = 'settings_pb2'
    # @@protoc_insertion_point(class_scope:SettingCandidate.VoteRecord)
    ))
  ,
  DESCRIPTOR = _SETTINGCANDIDATE,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:SettingCandidate)
  ))
_sym_db.RegisterMessage(SettingCandidate)
_sym_db.RegisterMessage(SettingCandidate.VoteRecord)

SettingCandidates = _reflection.GeneratedProtocolMessageType('SettingCandidates', (_message.Message,), dict(
  DESCRIPTOR = _SETTINGCANDIDATES,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:SettingCandidates)
  ))
_sym_db.RegisterMessage(SettingCandidates)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032sawtooth.settings.protobufP\001'))
# @@protoc_insertion_point(module_scope)
