REST_API_URL = 'http://rest-api:8080'
KEY_DIR = '/root/.sawtooth/keys'
PRIV_KEY_FILE = KEY_DIR + '/key.priv'
PUB_KEY_FILE = KEY_DIR + '/key.pub'

SETTINGS_PUB_KEY_ENCRYPTION = 'SETTINGS_PUB_KEY_ENCRYPTION'
SETTINGS_KEY_GENESIS_OWNERS = 'SETTINGS_KEY_GENESIS_OWNERS'
SETTINGS_SWAP_COMMISSION = 'SETTINGS_SWAP_COMMISSION'

ZERO_ADDRESS = '0' * 70
GENESIS_ADDRESS = '0' * 69 + '1'
